unstable_features = true
reorder_imports = true
wrap_comments = true
comment_width = 120
# Replace strings of _ wildcards by a single .. in tuple patterns
condense_wildcard_suffixes = true
# Error if Rustfmt is unable to get all lines within max_width, except for comments and string literals
error_on_line_overflow = true
# Format code snippet included in doc comments.
format_code_in_doc_comments = true
# Convert /* */ comments to // comments where possible
normalize_comments = true
# Convert #![doc] and #[doc] attributes to //! and /// doc comments.
normalize_doc_attributes = true
imports_granularity = "Crate"
