name: Security audit
on:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: '0 0 * * *'
  push:
    paths:
      # Run if workflow changes
      - '.github/workflows/audit.yml'
      # Run on changed dependencies
      - '**/Cargo.toml'
      # Run if the configuration file changes
      - '**/audit.toml'
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@v1


