name: Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks
    timeout-minutes: 10080
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        name: Run Benchmarks
        with:
          command: bench
          args: --all-features
